namespace SolutionRunner.LCAttributes;

[AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct, AllowMultiple = false, Inherited = false)]
public sealed class LeetCodeTagsAttribute(params LeetCodeTag[] tags) : Attribute {
    public LeetCodeTag[] Tags { get; } = tags ?? Array.Empty<LeetCodeTag>();
}

public enum LeetCodeTag
{
    Array,
    HashTable,
    String,
    Math,
    TwoPointers,
    Sorting,
    Greedy,
    DepthFirstSearch,
    BreadthFirstSearch,
    BinarySearch,
    DynamicProgramming,
    Backtracking,
    Stack,
    HeapPriorityQueue,
    Graph,
    Simulation,
    Design,
    Counting,
    PrefixSum,
    Matrix,
    BitManipulation,
    Tree,
    LinkedList,
    Recursion,
    SlidingWindow,
    MonotonicStack,
    UnionFind,
    Geometry,
    Enumeration,
    OrderedSet,
    NumberTheory,
    Combinatorics,
    DataStream,
    TopologicalSort,
    ShortestPath,
    SegmentTree,
    BinaryIndexedTree,
    Iterator,
    Trie,
    Memoization,
    ProbabilityAndStatistics,
    GameTheory,
    Interactive,
    DivideAndConquer,
    Queue,
    BinarySearchTree,
    DoublyLinkedList,
    BinaryTree,
    MergeSort,
    Quickselect,
    BucketSort,
    RadixSort,
    CountingSort,
    RollingHash,
    SuffixArray,
    HashFunction,
    MinimumSpanningTree,
    StronglyConnectedComponent,
    EulerianCircuit,
    BiconnectedComponent,
    Brainteaser,
    Randomized,
    RejectionSampling,
    ReservoirSampling
}
